### ISSUE TITLE
DiscordAPIError: Invalid Form Body

### ISSUE THREAD

**Issue by MondoPIX** [TheONLYGod1/FivemServerStatus#16]
```
[INFO] 853 players
DiscordAPIError: Invalid Form Body
embeds: Embed size exceeds maximum size of 6000
    at RequestHandler.execute (/home/botdiscord/FivemServerStatus-main/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/botdiscord/FivemServerStatus-main/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/botdiscord/FivemServerStatus-main/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
  method: 'post',
  path: '/channels/994335964497465355/messages',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: [Array],
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Comment by MondoPIX** [comment]
![image](https://user-images.githubusercontent.com/22109196/177639867-2f92fe6e-cd81-4ecb-b8d5-4edce5d67ad7.png)

**Comment by TheONLYGod1** [comment]
For now set the SHOW_PLAYERS to false to prevent this error. It's due to the amount of players on your server. I'll have to implement a check for the char limits.

**Comment by TheONLYGod1** [comment]
I know this issue was created 24 days ago, I am sorry, but are you able to test the edit I just pushed here https://github.com/TheONLYGod1/FivemServerStatus/tree/16-discordapierror-invalid-form-body ?
