### ISSUE TITLE
fields.flat

### ISSUE THREAD

**Issue by Scorpio-Vice** [TheONLYGod1/FivemServerStatus#5]
(node:121108) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/Disbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/Disbot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/Disbot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at UpdateEmbed (/home/Disbot/bot.js:142:6)
    at offline (/home/Disbot/bot.js:154:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:121108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by TheONLYGod1** [comment]
Update your node version

**Comment by TheONLYGod1** [comment]
Update your node version

**Comment by Zviux** [comment]
> Update your node version

how i update i`m lost.

**Comment by TheONLYGod1** [comment]
> > Update your node version
> 
> how i update i`m lost.

https://phoenixnap.com/kb/update-node-js-version

Google works wonders as well..
